CREATE USER hyundai IDENTIFIED BY hyundai
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    QUOTA 10m ON users
    QUOTA 10m ON apps;

GRANT
    CREATE SESSION,
    CREATE TABLE,
    CREATE PROCEDURE,
    CREATE TRIGGER,
    CREATE VIEW,
    CREATE SEQUENCE,
    CREATE TYPE
TO hyundai;